### ISSUE TITLE
Check all parameters and update wcs-manifest.json

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-meteo-generic#11]
Check for new parameters and integrate them in the wcs-manifest.json and do a new deployment on the testing store...

@dulvui

Please also accept the invitation to this repo

**Comment by dulvui** [comment]
Added new parameters **visibleTabs** and **startingTab** and deployed to WebStore.
startingTab is working but visibleTabs not.

**Comment by lcfd** [comment]
@dulvui Hi, try to check if the quotation marks are rightly used. The parameter needs `'`  marks.

**Comment by dulvui** [comment]
okay thanks for the hint.
Will check now

**Comment by Piiit** [comment]
@dulvui @lcfd The store gives always double quotes, so the parameters need to be with single marks inside

**Comment by Piiit** [comment]
Tonight I fixed the quotation issue inside the store... Let's see if we can get proper ticks tomorrow... Good night everybody

**Comment by dulvui** [comment]
All parameters checked and converted to correct format.
Seems to work on my side.

Ready for review.
