### ISSUE TITLE
filter icon is not clickable, that is no filter menu opens

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-meteo-generic#21]

**Comment by GnuRant** [comment]
@Piiit review

**Comment by Piiit** [comment]
@sseppi @GnuRant Filter Icon removed, works for me...

I see that the search does not work anymore, could that be a regression?

**Comment by Piiit** [comment]
We tackle the issue described in the comment above with https://github.com/noi-techpark/webcomp-meteo-generic/issues/18. This one is solved
