### ISSUE TITLE
As a Web component Store manager I want to have the Generic Meteo Web Component online

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-meteo-generic#3]
- [x] @Piiit Integrate webcomp-meteo-generic into the store
- [x] @Piiit CI pipeline missing

I know this is just the first MVP, so I think we are on a good way, just wanna quickly enumerate some issues :-)

First feedback/questions:
- [x] @lcfd No tiles shown, is there something to set in .env while building/developing/watching? How to use it with docker-compose up?
- [x] @lcfd README incomplete: switch to yarn for instance, describe all .env vars, .env.example missing
- [x] @lcfd Why are subsequent weather web comps not reused (that is, taken from our CDN directly), but copy/pasted?
    > Opened in a new issue #17
- [x] @sseppi wcs-manifest.json still misses some metadata

**Comment by Piiit** [comment]
@sseppi Done, please test: https://webcomponents.opendatahub.testingmachine.eu/webcomponent/8ed52ba6-ce1d-45c8-83bb-062d688b4326

The tiles and here map integration does not work, the documenation is incomplete... please see the updated to dos above

**Comment by Piiit** [comment]
@lcfd Hi, thanks for the first PR... please find some feedback inside the main comment... Cheers

**Comment by sseppi** [comment]
@lcfd I can't find in the configuration the possibility to activate or deactivate the single tabs "map", "Forecast", "Video".
Is it a feature that you are still working on?

**Comment by sseppi** [comment]
I add the link to the component on our testing environment:

https://webcomponents.opendatahub.testingmachine.eu/webcomponent/8ed52ba6-ce1d-45c8-83bb-062d688b4326

**Comment by lcfd** [comment]
@sseppi 

Hi! 

> I can't find in the configuration the possibility to activate or deactivate the single tabs

We should discuss with design and Luca D'Incà how to procede on that. This feature was not in my tasks.

**Comment by lcfd** [comment]
@sseppi @Piiit 

This should be solved

cc @gnurant
