### ISSUE TITLE
Combine sub-stations into a single station with a longer description

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/webcomp-meteo-generic#5]
Generic Meteo Widget shows all "sub-stations" as single dots on the map, should be combined as single detail

Many stations are just sub-modules of a single measruement station, that is for instance, that pressure and temperature should be the same dot on the map, just with a description of both values in the detail view.

**Comment by Piiit** [comment]
@GnuRant FYI

**Comment by lcfd** [comment]
I've noticed this behavior, the APIs are a bit confusing.
We can proceed for a fix, I'll ask you for some hints on how to aggregate those data. 
If I remember correctly we are using both mountain and mobility measuring points at the same time.

@Piiit

**Comment by Piiit** [comment]
@lcfd You could possible use "tree" visualization to get all measurement and types inside a single station JSON object...
For example: `GET https://mobility.api.opendatahub.bz.it/v2/tree,node/MeteoStation/*`... with that you do not need to do the grouping inside JS.

I have also seen that you used the WHERE clause multiple times inside the same call, this is not possible. You should just have them divided with commas. See https://docs.opendatahub.bz.it/en/latest/howto/mobility/getstarted.html#get-started-mobility for details...

I suggest to also use SELECT, such that we only download things we really need. Please drop me a comment, if you have questions.

**Comment by Piiit** [comment]
Example query could be:
```http
GET https://mobility.api.opendatahub.bz.it/v2/tree,node/MeteoStation/*
?where=sactive.eq.true
&select=tname,tunit,tdescription,scoordinate,sname
```

**Comment by lcfd** [comment]
@Piiit Thank you, I'm trying those endpoints with promising results. 
On the docs I can't find instructions on language management, is there any way to get translations?

**Comment by Piiit** [comment]
@lcfd No, I am sorry, we do not have any facilities for translations. Everything we have are those strings inside metadata, sometimes inside names (unfortunately, these data are just retrieved from 3rd party endpoints, and therefore not standardized, nor with a unified language)... At the moment we should therefore just focus on translations of the hardcoded JS parts and eventually use languages if they are present inside the metadata JSON objects.

**Comment by lcfd** [comment]
> At the moment we should therefore just focus on translations of the hardcoded JS parts and eventually use languages if they are present inside the metadata JSON objects.

All the hard-coded translations are in the `code/translations.js` files. Give them a look in every repository paying attention to German that it's the most delicate part.

@Piiit @GnuRant

**Comment by lcfd** [comment]
@sseppi 

This issue was solved with a previous PR.

cc @gnurant
