### ISSUE TITLE
Some configuration are missing

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/webcomp-meteo-generic#9]
According to the Briefing sent some configurations of the web component on the web component store are missing.

In particular actually for a web component store user are missing the following configuration opportunity:
- [x] select between real time data or forecast. This could be maybe solved by giving the possibility to the web component store user to activate/deactivate the singe "tabs" (Map, Video, etc.);
- [x] in case of the real time data select the types of data type (e.g. temperature, humidity, etc.) to be shown;
- [x] select the station/location to be shown. In case of real data the user should input the IDs of the stations that has to be shown in the map. In case of forecast the user should input, maybe trough a drop down menu, the area he is interested to show in the web component.

@GnuRant

**Comment by lcfd** [comment]
Hi @sseppi, point 1 should already be or in pr or merged

Point 2 and 3 we are checking

cc @gnurant

**Comment by sseppi** [comment]
@lcfd @GnuRant if we put more the one station ID the web component doesn't show any result.

In the configuration configuration it should be possible to put more than one ID as CSV and the web component should show all station listed in the configuration.

**Comment by Piiit** [comment]
Format example: `abc,cde` and not `["abc","cde"]`

**Comment by Piiit** [comment]
@lcfd @sseppi @GnuRant Works, thanks
